version: '3'

networks:
  basic:

services:
  db:
    image: mysql:5.7
    networks:
      - basic
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  api:
    image: node:20.12.2
    networks:
      - basic
    depends_on:
      - db
    ports:
      - ${API_SERVER_PORT}:3000
    volumes:
      - ./server:/server
    tty: true
    working_dir: /server
    environment:
      TZ: Asia/Tokyo
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DOMAIN: 'db'
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      BLOCKCHAIN_API: ${BLOCKCHAIN_API}
      ERC1155_ADDRESS: ${ERC1155_ADDRESS}
      GASHA_ADDRESS: ${GASHA_ADDRESS}
      NEYNAR_API_KEY: ${NEYNAR_API_KEY}
      CLIENT_URL: ${CLIENT_URL}
      CHAIN_ID: ${CHAIN_ID}
      UPDATE_SCORE_INTERVAL_MINUTES: ${UPDATE_SCORE_INTERVAL_MINUTES}
      THIRDWEB_ENGINE_ENDPOINT: ${THIRDWEB_ENGINE_ENDPOINT}
      THIRDWEB_ENGINE_ACCESS_TOKEN: ${THIRDWEB_ENGINE_ACCESS_TOKEN}
      WAR_CONTRACT_ADDRESS: ${WAR_CONTRACT_ADDRESS}
      DEALER_PRIVATE_KEY: ${DEALER_PRIVATE_KEY}
      ENGINE_WALLET_ADDRESS: ${ENGINE_WALLET_ADDRESS}
      ENGINE_WEBHOOK_SECRET: ${ENGINE_WEBHOOK_SECRET}
      FARCASTER_SIGNER_UUID: ${FARCASTER_SIGNER_UUID}
      INVITATION_CONTRACT_ADDRESS: ${INVITATION_CONTRACT_ADDRESS}
      STREAM_INTERVAL_MINUTES: ${STREAM_INTERVAL_MINUTES}
      STREAM_SCORING_CRON_EXPRESSION: ${STREAM_SCORING_CRON_EXPRESSION}
      STREAM_SET_SCHEDULE_CRON_EXPRESSION: ${STREAM_SET_SCHEDULE_CRON_EXPRESSION}
      STREAM_EXECUTE_SCHEDULE_CRON_EXPRESSION: ${STREAM_EXECUTE_SCHEDULE_CRON_EXPRESSION}
      STREAM_END_SCHEDULE_CRON_EXPRESSION: ${STREAM_END_SCHEDULE_CRON_EXPRESSION}
      FRAME_BASE_URL: ${FRAME_BASE_URL}
    command: yarn start:dev
