FROM node:18 AS builder
WORKDIR /usr/src/app

COPY ./server/package*.json ./
RUN npm install

COPY ./server ./
RUN npm run build

FROM node:18
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "run", "start:prod"]
