version: '3'

networks:
  basic:

services:
  frame:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run serve
  db_frame:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: card_frame
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./.tmp/mysql-data:/var/lib/mysql
    networks:
      - basic
    ports:
      - 3307:3307
